# alt_send_esc = true

[cursor]
style = "Block"
unfocused_hollow = true

[debug]
log_level = "Warn"
persistent_logging = false
print_events = false
render_timer = false

[env]
TERM = "xterm-256color"

[font]
size = 14.0

[font.glyph_offset]
x = 0
y = 0

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"

[font.offset]
x = 0
y = 0

[mouse]
hide_when_typing = false

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false
semantic_escape_chars = ''',│`|:"' ()[]{}<>'''

[window]
decorations = "none"
dynamic_padding = true
opacity = 0.9
startup_mode = "Windowed"

[window.padding]
x = 2
y = 0

[colors]
draw_bold_text_with_bright_colors = true

[general]
live_config_reload = true
working_directory = "None"
import = ["/Users/maximilianodimito/.config/alacritty/./rose-pine.yml"]
