require('user.configs')
require('user.keymaps')
require('user.autocmds')
require('user.plugins')
require('user.autopairs')
require('user.bufferline')
require('user.comment')
require('user.fzf')
require('user.gitsigns')
require('user.indent-blankline')
require('user.hop')
require('user.nvim-tree')
require('user.treesitter')
require('user.lsp-zero')
require('user.which-key')
require('user.null-ls')

pcall(vim.cmd, 'colorscheme gruvbox-flat')
require('user.lualine')
